site_name: Multilingual LLM Playbook

theme:
  name: material
  language: en
  features:
    - navigation.tabs
    - navigation.top
    - toc.integrate
    - content.code.copy
    - content.code.annotate
    - search.suggest
    - navigation.sections
    - content.footnote.tooltips
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night   # 🌙 icon for dark mode
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny   # ☀️ icon for light mode
        name: Switch to light mode


nav:
  - Home: index.md
  - Playbook:
      - Introduction: chapters/00-introduction.md
      - Evaluation: chapters/01-evaluation.md
      - Translation: chapters/02-translation.md
      - Off-the-shelf LLMs: chapters/03-off-the-shelf.md
      - Fine-tuning LLMs: chapters/04-fine-tuning.md
      - Conclusion: chapters/99-conclusion.md
  - Interactive Flowchart: interactive/flowchart.md

plugins:
  - search
  - print-site:
      path_to_pdf: "assets/playbook.pdf"
  - to-pdf
  - glightbox
  - bibtex:
      bib_file: docs/references.bib     # or a list of .bib files
      # optional:
      # csl_file: docs/ieee.csl
      # bib_by_default: true            # auto-append refs on every page



markdown_extensions:
  - attr_list
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.details
  - admonition
  - toc:
      permalink: true
      toc_depth: 2-4
  - footnotes

extra_javascript:
  - https://unpkg.com/mermaid@10.4.0/dist/mermaid.min.js
