"""
Shared normalization lookup dictionaries for the multilingual benchmark analysis.

These maps canonicalize the heterogeneous raw values found across contributor
JSONs (papers_metadata/extracted/) into a consistent controlled vocabulary.
Used by normalize.py (and potentially audit_metadata.py or website tooling).
"""

# ── Benchmark display names ──────────────────────────────────────────────────

BENCHMARK_NAME_MAP = {
    "bemycheese_extracted": "BeMyCheese",
    "culturalbench_extracted": "CulturalBench",
    "fluidqa_extracted": "FluidQA",
    "iberobench_extracted": "IberoBench",
    "maxife_extracted": "MaXIFE",
    "mmteb_extracted": "MMTEB",
    "much_extracted": "MUCH",
    "seahelm_extracted": "SeaHELM",
    "MILU (Multi-task Indic Language Understanding Benchmark)": "MILU",
    "MultiJail (Multilingual Jailbreak Dataset)": "MultiJail",
    "PolygloToxicityPrompts (PTP)": "PTP",
    "CL-IFEval / CL-GSMSym": "CL-IFEval",
    "Uhura": "Uhuru",
}

# ── Language family normalization ────────────────────────────────────────────

FAMILY_NORM = {
    # Indo-European sub-family variants → Indo-European
    "Indo-Aryan": "Indo-European",
    "Indo-European (Indo-Aryan)": "Indo-European",
    "Indo-European (Romance)": "Indo-European",
    "Indo-European / Germanic": "Indo-European",
    "Indo-European / Romance": "Indo-European",
    "Indo-European / Slavic": "Indo-European",
    "Indo-European / Indo-Aryan": "Indo-European",
    "Indo-European / Baltic": "Indo-European",
    "Indo-European / Celtic": "Indo-European",
    "Indo-European / Hellenic": "Indo-European",
    "Indo-Aryan (Indo-European)": "Indo-European",
    "Germanic (Indo-European)": "Indo-European",
    "IE: Baltic": "Indo-European",
    "IE: Germanic": "Indo-European",
    "IE: Greek": "Indo-European",
    "IE: Indo-Aryan": "Indo-European",
    "IE: Iranian": "Indo-European",
    "IE: Romance": "Indo-European",
    "IE: Slavic": "Indo-European",
    "Indic": "Indo-European",
    # Afro-Asiatic sub-families
    "Semitic": "Afro-Asiatic",
    "Chadic": "Afro-Asiatic",
    "Afro-Asiatic / Chadic": "Afro-Asiatic",
    "Afro-Asiatic / Cushitic": "Afro-Asiatic",
    "Afro-Asiatic / Semitic": "Afro-Asiatic",
    # Niger-Congo
    "Bantu": "Niger-Congo",
    "Atlantic-Congo": "Niger-Congo",
    "Niger-Congo / Atlantic-Congo": "Niger-Congo",
    "Niger-Congo / Bantu": "Niger-Congo",
    # Austroasiatic variants
    "Austro-Asiatic": "Austroasiatic",
    "Austroasiatic / Mon-Khmer": "Austroasiatic",
    # Austronesian variants
    "Austronesian / Malayo-Polynesian": "Austronesian",
    # Kra-Dai variants
    "Tai-Kadai": "Kra-Dai",
    "Kra-Dai / Tai-Kadai": "Kra-Dai",
    # Creole variants
    "Indo-European (English Creole)": "Creole",
    "English-Creole": "Creole",
    "English Creole": "Creole",
    "French Creole": "Creole",
    # Koreanic variants
    "Koreanic (isolate)": "Koreanic",
    # Basque
    "Basque (isolate)": "Basque",
    # Turkic
    "Altaic": "Turkic",
    # Other/misc
    "other": "Unknown",
    "None": "Unknown",
}

# ── Script normalization ─────────────────────────────────────────────────────

SCRIPT_NORM = {
    # CJK / Chinese
    "Han": "CJK",
    "Simplified Han": "CJK",
    "Traditional Han": "CJK",
    "Simplified Chinese": "CJK",
    "Traditional Chinese": "CJK",
    "Chinese characters": "CJK",
    "Chinese characters (Hanzi)": "CJK",
    "Chinese characters (Han)": "CJK",
    "Han (Chinese characters)": "CJK",
    "Chinese ideograms": "CJK",
    "Ideograms": "CJK",
    "Simplified Chinese / Traditional Chinese": "CJK",
    # Japanese
    "Japanese (Kanji/Hiragana/Katakana)": "CJK / Kana",
    "Kanji/Hiragana/Katakana": "CJK / Kana",
    "Japanese": "CJK / Kana",
    "Mixed (Chinese characters, Hiragana, Katakana)": "CJK / Kana",
    "Mixed (Kanji, Hiragana, Katakana)": "CJK / Kana",
    "Han/Hiragana/Katakana": "CJK / Kana",
    "Japanese (Kanji, Hiragana, Katakana)": "CJK / Kana",
    # Korean
    "Hangul": "Hangul",
    # Bengali
    "Bengali (Eastern Nagari)": "Bengali",
    "Bengali (Assamese variant)": "Bengali",
    "Bengali-Assamese": "Bengali",
    # Ethiopic
    "Ethiopic (Ge'ez)": "Ge'ez",
    "Ethiopic": "Ge'ez",
    "Geez": "Ge'ez",
    # Georgian
    "Georgian (Mkhedruli)": "Georgian",
    # Arabic / Perso-Arabic
    "Perso-Arabic": "Arabic",
    "Perso-Arabic (Nastaliq)": "Arabic",
    "Nastaliq (Perso-Arabic)": "Arabic",
    "Arabic (Nastaliq)": "Arabic",
    "Arabic (Persian)": "Arabic",
    "Arabic alphabet": "Arabic",
    # Hebrew
    "Jewish (Hebrew)": "Hebrew",
    # Gurmukhi
    "Gurmukhi / Shahmukhi": "Gurmukhi",
    "Gurumukhi": "Gurmukhi",
    # Latin variants
    "Latin (Vietnamese)": "Latin",
    "Latin (Vietnamese alphabet)": "Latin",
    "Latin (Chữ Quốc Ngữ)": "Latin",
    "Latin (Quốc ngữ)": "Latin",
    "Latin (Boko)": "Latin",
    "Latin (also traditional Javanese script present in questions)": "Latin",
    "Modified Latin": "Latin",
    # Cyrillic variants
    "Serbian Cyrillic": "Cyrillic",
    "Cyrillic / Latin": "Cyrillic",
    "['Cyrillic', 'Latin']": "Cyrillic",
    # Thai
    "Thai (Abugida, non-Latin)": "Thai",
    # Myanmar
    "Myanmar": "Myanmar",
    # Brahmic
    "Brahmic": "Brahmic",
    # Multi-script list representations
    "['Latin', 'Arabic']": "Latin",
    "['Arabic', 'Latin']": "Arabic",
    # None/missing
    "None": "Unknown",
}

# ── Resource level normalization ─────────────────────────────────────────────

RESOURCE_NORM = {
    "high": "High",
    "medium": "Low-Moderate",
    "mid": "Low-Moderate",
    "moderate": "Low-Moderate",
    "low-moderate": "Low-Moderate",
    "low": "Low",
    "very low": "Very Low",
    "very-low": "Very Low",
    "left-behind": "Very Low",
    "none": "Unknown",
    "unknown": "Unknown",
}

# ── Region → Continent mapping ───────────────────────────────────────────────

REGION_TO_CONTINENT = {
    # Sub-Saharan Africa — general
    "Africa": "Sub-Saharan Africa",
    "West Africa": "Sub-Saharan Africa",
    "West Africa (Nigeria)": "Sub-Saharan Africa",
    "West Africa (Nigeria, Niger)": "Sub-Saharan Africa",
    "West/Central Africa": "Sub-Saharan Africa",
    "East Africa": "Sub-Saharan Africa",
    "East Africa (Ethiopia)": "Sub-Saharan Africa",
    "East Africa (Kenya)": "Sub-Saharan Africa",
    "East Africa (Somalia)": "Sub-Saharan Africa",
    "East Africa (Tanzania)": "Sub-Saharan Africa",
    "East Africa (Kenya, Tanzania)": "Sub-Saharan Africa",
    "East Africa (Madagascar)": "Sub-Saharan Africa",
    "East Africa (Rwanda)": "Sub-Saharan Africa",
    "East Africa (Uganda)": "Sub-Saharan Africa",
    "East/Central Africa": "Sub-Saharan Africa",
    "South-East Africa": "Sub-Saharan Africa",
    "South/East Africa": "Sub-Saharan Africa",
    "Southern Africa": "Sub-Saharan Africa",
    "Southern Africa (South Africa)": "Sub-Saharan Africa",
    "Southern/Central Africa": "Sub-Saharan Africa",
    "Southern/East/Central Africa": "Sub-Saharan Africa",
    "Central Africa": "Sub-Saharan Africa",
    "South Africa": "Sub-Saharan Africa",
    "Sub-Saharan Africa": "Sub-Saharan Africa",
    "Horn of Africa": "Sub-Saharan Africa",
    "Sahel": "Sub-Saharan Africa",
    "Nigeria": "Sub-Saharan Africa",
    "Niger": "Sub-Saharan Africa",
    "Kenya": "Sub-Saharan Africa",
    "Madagascar": "Sub-Saharan Africa",
    "Ethiopia": "Sub-Saharan Africa",
    "Tanzania": "Sub-Saharan Africa",
    "Ghana": "Sub-Saharan Africa",
    "Cameroon": "Sub-Saharan Africa",
    "Senegal": "Sub-Saharan Africa",
    "Rwanda": "Sub-Saharan Africa",
    "Uganda": "Sub-Saharan Africa",
    "Mozambique": "Sub-Saharan Africa",
    "Zimbabwe": "Sub-Saharan Africa",
    "Zambia": "Sub-Saharan Africa",
    "Malawi": "Sub-Saharan Africa",
    "Somalia": "Sub-Saharan Africa",
    "Benin": "Sub-Saharan Africa",
    "Botswana": "Sub-Saharan Africa",
    "Democratic Republic of Congo": "Sub-Saharan Africa",
    "Republic of Congo": "Sub-Saharan Africa",
    "Eswatini": "Sub-Saharan Africa",
    "Namibia": "Sub-Saharan Africa",
    "Togo": "Sub-Saharan Africa",
    "Southern Africa (Angola)": "Sub-Saharan Africa",
    "West Africa (Cape Verde)": "Sub-Saharan Africa",
    "West Africa (Mali)": "Sub-Saharan Africa",
    # North Africa / Middle East
    "North Africa": "Middle East & North Africa",
    "Middle East": "Middle East & North Africa",
    "Middle East (Israel)": "Middle East & North Africa",
    "Middle East / North Africa": "Middle East & North Africa",
    "Iran": "Middle East & North Africa",
    "Israel": "Middle East & North Africa",
    "Saudi Arabia": "Middle East & North Africa",
    "Egypt": "Middle East & North Africa",
    "Iraq": "Middle East & North Africa",
    "United Arab Emirates": "Middle East & North Africa",
    "Western Asia": "Middle East & North Africa",
    "Middle East (Iraq)": "Middle East & North Africa",
    "Middle East (Levant)": "Middle East & North Africa",
    "Middle East (Saudi Arabia)": "Middle East & North Africa",
    "North Africa (Egypt)": "Middle East & North Africa",
    # South Asia (country + state + descriptive)
    "India": "South Asia",
    "South Asia": "South Asia",
    "Pakistan": "South Asia",
    "Bangladesh": "South Asia",
    "Nepal": "South Asia",
    "Sri Lanka": "South Asia",
    "Afghanistan": "South Asia",
    "Odisha": "South Asia",
    "Himachal Pradesh": "South Asia",
    "Uttar Pradesh": "South Asia",
    "Andhra Pradesh": "South Asia",
    "Tamil Nadu": "South Asia",
    "Kerala": "South Asia",
    "Karnataka": "South Asia",
    "West Bengal": "South Asia",
    "Gujarat": "South Asia",
    "Maharashtra": "South Asia",
    "Punjab": "South Asia",
    "Rajasthan": "South Asia",
    "Assam": "South Asia",
    "Bihar": "South Asia",
    "Goa": "South Asia",
    "Jharkhand": "South Asia",
    "Manipur": "South Asia",
    "Sikkim": "South Asia",
    "Telangana": "South Asia",
    "Jammu and Kashmir": "South Asia",
    "North India": "South Asia",
    "South India": "South Asia",
    "East India": "South Asia",
    "West India": "South Asia",
    "Central India": "South Asia",
    "Northeast India": "South Asia",
    "Pan-India": "South Asia",
    "Pan-India (classical, no single geographic region)": "South Asia",
    "pan-India administrative and educational use": "South Asia",
    "used in professional and competitive contexts nationally": "South Asia",
    "India (Andhra Pradesh, Telangana)": "South Asia",
    "India (Assam)": "South Asia",
    "India (Gujarat)": "South Asia",
    "India (Karnataka)": "South Asia",
    "India (Kerala)": "South Asia",
    "India (Maharashtra)": "South Asia",
    "India (Odisha)": "South Asia",
    "India (Punjab)": "South Asia",
    "India (Tamil Nadu)": "South Asia",
    "India (West Bengal)": "South Asia",
    "India (diaspora)": "South Asia",
    "Punjab (India)": "South Asia",
    "Punjab (Pakistan)": "South Asia",
    "Sindh (Pakistan)": "South Asia",
    "Pakistan (Punjab)": "South Asia",
    "South Asia (classical)": "South Asia",
    "South Asia (Nepal)": "South Asia",
    "South Asia (Sri Lanka)": "South Asia",
    "South Asia (Bangladesh, India \u2014 West Bengal)": "South Asia",
    "South Asia (Bangladesh, West Bengal)": "South Asia",
    "South Asia (India \u2014 Gujarat)": "South Asia",
    "South Asia (India \u2014 Hindi Belt / North India)": "South Asia",
    "South Asia (India \u2014 Karnataka)": "South Asia",
    "South Asia (India \u2014 Kerala)": "South Asia",
    "South Asia (India \u2014 Maharashtra)": "South Asia",
    "South Asia (India \u2014 Odisha)": "South Asia",
    "South Asia (India \u2014 Punjab)": "South Asia",
    "South Asia (India \u2014 Tamil Nadu)": "South Asia",
    "South Asia (India \u2014 Telangana, Andhra Pradesh)": "South Asia",
    "South Asia (India \u2014 West Bengal)": "South Asia",
    "South Asia (India \u2014 pan-India)": "South Asia",
    "South Asia (Eastern India)": "South Asia",
    "South Asia (Eastern India, Bangladesh)": "South Asia",
    "South Asia (India)": "South Asia",
    "South Asia (Nepal, India)": "South Asia",
    "South Asia (Northeast India)": "South Asia",
    "South Asia (Northern India)": "South Asia",
    "South Asia (Northern India, Pakistan)": "South Asia",
    "South Asia (Southern India)": "South Asia",
    "South Asia (Southern India, Sri Lanka)": "South Asia",
    "South Asia (Western India)": "South Asia",
    # Southeast Asia
    "Southeast Asia": "Southeast Asia",
    "Indonesia": "Southeast Asia",
    "Indonesia (Java)": "Southeast Asia",
    "Indonesia (West Java)": "Southeast Asia",
    "Vietnam": "Southeast Asia",
    "Thailand": "Southeast Asia",
    "Philippines": "Southeast Asia",
    "Malaysia": "Southeast Asia",
    "Singapore": "Southeast Asia",
    "Myanmar": "Southeast Asia",
    "Cambodia": "Southeast Asia",
    "Laos": "Southeast Asia",
    "Brunei": "Southeast Asia",
    "Southeast Asia (Indonesia)": "Southeast Asia",
    "Southeast Asia (Indonesia \u2014 Java)": "Southeast Asia",
    "Southeast Asia (Malaysia, Singapore)": "Southeast Asia",
    "Southeast Asia (Myanmar)": "Southeast Asia",
    "Southeast Asia (Thailand)": "Southeast Asia",
    "Southeast Asia (Vietnam)": "Southeast Asia",
    "Southeast Asia (Philippines)": "Southeast Asia",
    # East Asia
    "East Asia": "East Asia",
    "China": "East Asia",
    "Japan": "East Asia",
    "South Korea": "East Asia",
    "North Korea": "East Asia",
    "Taiwan": "East Asia",
    "Hong Kong": "East Asia",
    "Mongolia": "East Asia",
    "Xinjiang": "East Asia",
    "East Asia (China)": "East Asia",
    "East Asia (Japan)": "East Asia",
    "East Asia (Korea)": "East Asia",
    "East Asia (South Korea, North Korea)": "East Asia",
    "East Asia (Mongolia)": "East Asia",
    "East Asia (Tibet)": "East Asia",
    # Central Asia
    "Central Asia": "Central Asia",
    "Central Asia (Kyrgyzstan)": "Central Asia",
    "Kazakhstan": "Central Asia",
    "Uzbekistan": "Central Asia",
    "Kyrgyzstan": "Central Asia",
    "Tajikistan": "Central Asia",
    # Europe
    "Europe": "Europe",
    "Eastern Europe": "Europe",
    "Western Europe": "Europe",
    "Northern Europe": "Europe",
    "Northern Europe (Baltics)": "Europe",
    "Southern Europe": "Europe",
    "Southern Europe (Italy)": "Europe",
    "Southeastern Europe": "Europe",
    "Central Europe": "Europe",
    "Iberian Peninsula": "Europe",
    "Europe (Italy)": "Europe",
    "Germany": "Europe",
    "France": "Europe",
    "France (southern)": "Europe",
    "France (French Basque Country)": "Europe",
    "Italy": "Europe",
    "Spain": "Europe",
    "Spain (Basque Country)": "Europe",
    "Spain (Catalonia)": "Europe",
    "Spain (Catalonia, Balearic Islands, Valencia)": "Europe",
    "Spain (Galicia)": "Europe",
    "Spain (Iberian Peninsula)": "Europe",
    "Portugal": "Europe",
    "Netherlands": "Europe",
    "Belgium": "Europe",
    "Switzerland": "Europe",
    "Austria": "Europe",
    "Sweden": "Europe",
    "Romania": "Europe",
    "United Kingdom": "Europe",
    "United Kingdom (Wales)": "Europe",
    "Western Europe (France)": "Europe",
    "Western Europe (Ireland)": "Europe",
    "Western Europe (Spain)": "Europe",
    "Western Europe (Spain/France)": "Europe",
    "Western Europe (UK)": "Europe",
    "Southern Europe (Malta)": "Europe",
    "Turkey": "Europe",
    "Greece": "Europe",
    "Finland": "Europe",
    "Hungary": "Europe",
    "Czech Republic": "Europe",
    "Czechia": "Europe",
    "Serbia": "Europe",
    "Bulgaria": "Europe",
    "Estonia": "Europe",
    "Georgia": "Europe",
    "Balkans": "Europe",
    "Baltic states": "Europe",
    "Basque Country": "Europe",
    "Andorra": "Europe",
    "Armenia": "Europe",
    "Azerbaijan": "Europe",
    "Caucasus": "Europe",
    "South Caucasus": "Europe",
    "Crimea": "Europe",
    "Croatia": "Europe",
    "Cyprus": "Europe",
    "Denmark": "Europe",
    "Faroe Islands (Denmark)": "Europe",
    "Iceland": "Europe",
    "Ireland": "Europe",
    "Latvia": "Europe",
    "Lithuania": "Europe",
    "Malta": "Europe",
    "Moldova": "Europe",
    "North Macedonia": "Europe",
    "Norway": "Europe",
    "Poland": "Europe",
    "Russia": "Europe",
    "Northern Asia": "Europe",
    "Tatarstan": "Europe",
    "Slovakia": "Europe",
    "Slovenia": "Europe",
    "Ukraine": "Europe",
    # Americas
    "Americas": "Americas",
    "Latin America": "Americas",
    "South America": "Americas",
    "South America (Andean)": "Americas",
    "South America (Andes)": "Americas",
    "South America (Brazil)": "Americas",
    "Central America": "Americas",
    "North America": "Americas",
    "North America (United States)": "Americas",
    "Caribbean": "Americas",
    "Brazil": "Americas",
    "Mexico": "Americas",
    "United States": "Americas",
    "Canada": "Americas",
    "Colombia": "Americas",
    "Peru": "Americas",
    "Bolivia": "Americas",
    "Argentina": "Americas",
    "Chile": "Americas",
    "Paraguay": "Americas",
    "South America (Paraguay)": "Americas",
    # Oceania
    "Oceania": "Oceania",
    "Australia": "Oceania",
    "New Zealand": "Oceania",
    "Oceania (New Zealand)": "Oceania",
    # Global / Other
    "Global": "Global / Other",
    "Global (45 countries/regions)": "Global / Other",
    "Worldwide": "Global / Other",
    "Global (English-speaking)": "Global / Other",
}

# ── Task categorization ──────────────────────────────────────────────────────
# Order matters: first match wins.  More specific categories come first to
# prevent broad keywords from stealing tasks (e.g. "bitext" before "flores").

# Keywords prefixed with r: are regex patterns (matched via re.search).
# All other entries are plain substrings (matched via `kw in text`).
#
# Use (?![a-z]) (negative lookahead) to allow keyword at end-of-string or
# followed by digits/punctuation, while blocking false substring matches
# inside longer words.  E.g. r:ner(?![a-z]) matches NER, MASAKHANER
# but not "generation".
TASK_CATEGORIES = {
    "Embedding / Retrieval": [
        "embedding", "retrieval", "rerank", "cluster", "semantic similarity",
        "bitext", "tatoeba", "sts", "bucc", "sick-r", "biosses", "semrel",
        "twitter", "arguana", "trec", "scidocs", "fever", "wpr", "nexus", "mteb",
        r"r:xor(?![a-z])", "qadsm", "duplicate", "hotpotqa",
        "web page rank", "query-ad match",
    ],
    "NER": [r"r:ner(?![a-z])", "named entity", "wikiann", "pan-x", "naamapadam", "mewsli"],
    "QA / Knowledge": [
        r"r:qa(?![a-z])", "question answering", "question", "knowledge",
        "reading comprehension", "commonsense", "truthful", r"r:mcq(?![a-z])",
        "mmlu", "m3exam", "quad", "fill in the blank", "match the column",
        "rearrange", "legalbench", "parsi", "headline prediction", "prediction",
        r"r:(?<![a-z])qam(?![a-z])", "twenty questions",
    ],
    "NLI / Inference": [
        r"r:nli(?![a-z])", "entailment", "inference", "paraphras", "parafras", "paws",
        "copa", "storycloze", "winograd", "wino-mt", r"r:rte(?![a-z])", "terra",
        "opusparcus", "jsick", "ppcpc", "curev1",
    ],
    "Sentiment / Classification": [
        "senti", "classif", "topic", "intent", "slot", "polemo",
        "amazon", "cultural", r"r:(?<![a-z])nc(?![a-z])",
    ],
    "Translation": [
        "translation", r"r:(?<![a-z])mt(?![a-z])", "machine translation", "flores",
    ],
    "Summarization": [
        "summar", "xl-sum", "xlsum", r"r:(?<![a-z])ntg(?![a-z])",
        "title generation", r"r:(?<![a-z])psc(?![a-z])",
    ],
    "Safety / Toxicity": [
        "safety", "toxic", "hate", "jailbreak", "harmful", "jail", "oversensitiv",
        "hallucination", "factual", "jigsaw", "uncertainty", "fake",
        r"r:(?<![a-z])cbd(?![a-z])", r"r:(?<![a-z])pac(?![a-z])",
    ],
    "Instruction Following": ["instruction follow", "ifeval", "constrained generation", "instruction_following"],
    "Math / Reasoning": ["math", "reasoning", "causal", "mgsm"],
    "Coding": ["humaneval", "livecodebench", "code", "sql", "tool_use"],
    "Generation": [
        "generation", "open-ended", "chat", "arena", "dolly", r"r:(?<![a-z])aya(?![a-z])",
        r"r:(?<![a-z])qg(?![a-z])", "question generation",
    ],
    "Linguistic Probing": [
        "linguistic", "diagnostics", "morphol", "pragmat", "figurative",
        "metaphor", "dialect", "part-of-speech", r"r:pos(?![a-z])", "diacrit",
        "transliter", "perplexity", "language model", "pretraining",
        "code-switch", "en-es-cs", "claim", "segmenta", "ruler",
    ],
    "Speech": [r"r:(?<![a-z])asr(?![a-z])", "speech", r"r:(?<![a-z])ocr(?![a-z])", "spoken", "optical_character_recognition"],
}
