const fs = require('fs');
const path = require('path');

const root = path.resolve(__dirname, '..');
const chaptersDir = path.join(root, 'public', 'chapters');
const docsDir = path.join(root, 'components', 'docs');
const docIndexFile = path.join(docsDir, 'docIndex.js');
const mainFile = path.join(root, 'main.jsx');

if (!fs.existsSync(chaptersDir)) {
    console.error('chapters directory not found:', chaptersDir);
    process.exit(1);
}
if (!fs.existsSync(mainFile)) {
    console.error('main.jsx not found:', mainFile);
    process.exit(1);
}

function titleize(str) {
    return str.split(/[-_]/).map(s => s.replace(/\b\w/g, ch => ch.toUpperCase())).join(' ').replace(/\bAsr\b/i, 'ASR');
}

// Read chapters
const mdFiles = fs.readdirSync(chaptersDir).filter(f => f.endsWith('.md'))
    .sort((a, b) => {
        // sort by leading numeric prefix then ensure numeric parent comes
        // before roman-numeral subentries (e.g. 08-model... before 08-i-...)
        const na = a.match(/^([0-9]+)-/); const nb = b.match(/^([0-9]+)-/);
        const ia = na ? parseInt(na[1], 10) : 9999;
        const ib = nb ? parseInt(nb[1], 10) : 9999;
        if (ia !== ib) return ia - ib;
        // same numeric prefix: detect roman-numeral subentries
        const subRe = /^\d+-(?:i|ii|iii|iv|v|vi|vii|viii|ix|x)-/;
        const aIsSub = subRe.test(a);
        const bIsSub = subRe.test(b);
        if (aIsSub !== bIsSub) {
            // put non-sub first
            return aIsSub ? 1 : -1;
        }
        return a.localeCompare(b);
    });

if (mdFiles.length === 0) {
    console.log('No chapters found.');
    process.exit(0);
}

// Build entries
const ACRONYMS = ['ASR', 'NLP', 'API', 'HTTP', 'URL', 'ID'];
// Default icon map for common roots (can be edited later in docIndex)
const DEFAULT_ICON_BY_BASE = {
    '02-evolution-of-asr': 'Branch24Regular',
    '04-dataset-creation-guidelines': 'Add24Regular',
    '08-model-finetuning-intro': 'Options24Regular',
    '09-inference': 'PlugConnected24Regular',
    '10-data-augmentation': 'Wand24Regular'
};

const entries = mdFiles.map(f => {
    const base = f.replace(/\.md$/, '');
    // label: remove leading digits and dash
    const labelPart = base.replace(/^[0-9]+-/, '');
    // if starts with a small roman or letter segment like i-, ii- treat as simple
    const label = titleize(labelPart.replace(/^i-/, '').replace(/^ii-/, '').replace(/^iii-/, '').replace(/^iv-/, ''));
    // build component name but honor known acronyms (ASR -> ASR)
    const rawParts = labelPart.split(/[^a-zA-Z0-9]+/).filter(Boolean);
    const pascalParts = rawParts.map(s => {
        const up = s.toUpperCase();
        if (ACRONYMS.includes(up)) return up;
        return s.charAt(0).toUpperCase() + s.slice(1);
    });
    const compName = (pascalParts.join('') || 'Doc') + 'Doc';
    const prefixMatch = base.match(/^(\d{2})-/);
    const prefix = prefixMatch ? prefixMatch[1] : null;
    const isSub = /^\d+-(?:i|ii|iii|iv|v|vi|vii|viii|ix|x)-/.test(base);
    const icon = !isSub ? (DEFAULT_ICON_BY_BASE[base] || 'Document24Regular') : null;
    return { content: `/public/chapters/${f}`, base, route: `/playbook/${base}`, compName, label, isSub, prefix, icon };
});

const docEntries = entries.map(e => ({ path: e.route, label: e.label, base: e.base, content: e.content, prefix: e.prefix, isSub: e.isSub, icon: e.icon }));
const docOrder = docEntries.map(e => ({ path: e.path, label: e.label }));
const indexSrc = `// Auto-generated by scripts/sync-index.js\n// Do not edit manually; run the sync script after changing chapters.\n\nexport const docEntries = ${JSON.stringify(docEntries, null, 2)};\n\nexport const docOrder = ${JSON.stringify(docOrder, null, 2)};\n`;
fs.writeFileSync(docIndexFile, indexSrc, 'utf8');
console.log('Wrote doc index:', docIndexFile);